### ISSUE TITLE
Improve Docroot documentation and interactive mode

### ISSUE THREAD

**Issue by jameswilson** [terra-ops/terra-cli#114]
It wasn't obvious to me that the Docroot option in `environment:add` command is supposed to be reporoot relative.  I specified it as a fully qualified path, and it had no effect.  Additionally, there is no way in interactive mode to add a different Docroot folder.

The only way I was able to get an app working that had a Docroot different from the repo root was by adding an app and environment that already had a `.terra.yml` file in the repo root that specified a different `document_root`.

I think this option should be exposed to the interactive mode, and the documentation in the command help could be improved (maybe with an example?) to make it more obvious that the path is supposed to be relative to the repo root.

**Comment by jonpugh** [comment]
Totally agreed here, I ran into this issue when helping friends try out terra.

I did a little bit of work to get this started... but I can't do the work myself right now.

I'm very liberal about accepting pull requests, however, and after just one, I'd be happy to grant full access!
...

Thanks a ton for your patience, and for coming back and posting this issue. I know it's been a while since there's been activity, but I promise, we are not abandoning this project.

**Comment by jameswilson** [comment]
Thanks for your work on this, and for the very encouraging reply @jonpugh.  I _really_ like Terra's architecture. It is very well thought out and executed.

**Comment by jonpugh** [comment]
Looks like this was merged so... closing!

**Comment by jameswilson** [comment]
I was thinking this should still be open, and just improve the documentation a little tiny bit for document_root

```
$ terra help env:add
Usage:
  environment:add [options] [--] [<app_name>] [<environment_name>] [<path>] [<document_root>]

Arguments:
  app_name              The app you would like to add an environment for.
  environment_name      The name of the environment.
  path                  The path to the environment.
  document_root         The path to the web document root within the repository. [default: "/"]
```
