### ISSUE TITLE
Code style?

### ISSUE THREAD

**Issue by xendk** [terra-ops/terra-cli#15]
Terra seems to be using mostly Drupal Coding Standard style. Considering it's more of a Symfony Command project, can I suggest using PSR-2 instead?

**Comment by jonpugh** [comment]
:+1: on this one.

**Comment by jmolivas** [comment]
I will take care of making the code base PSR-2 code style compliant and provide a PHP Class and a pre-commit hook to execute when trying to commit code to the project.

**Comment by jmolivas** [comment]
Since the PR https://github.com/terra-ops/terra-app/pull/45 was merged

1) Should this be closed?

2) Wait for this: 

I am planing to send a new PR containing this https://github.com/hechoendrupal/DrupalConsole/blob/master/CodeQualityTool.php 

And also instructions how to add it to your pre-commit git-hook in order to check code before sneding a commit.
