### ISSUE TITLE
Do not promote as Aegir NG

### ISSUE THREAD

**Issue by cweagans** [terra-ops/terra-cli#46]
My personal opinion is that Terra doesn't accurately reflect the direction we agreed on in the AegirNG proposal, nor does the timing or community promotion. You started this project not very long ago and immediately started branding it as the successor to Aegir, and while that might eventually become the case, I think that it was a bit out of turn to do this before talking with the rest of the Aegir maintainers.

Furthermore, the entire point of the panel discussion that we're having this week is to get community buy-in on this direction so that people don't lose their shit about a major change in direction.

The technical issues can be debated later, but for now, I'd like to request that you not promote Terra as **the** successor to Aegir on the project page or at the Aegir summit. Let's at least talk about it with the community first, and incorporate the feedback that we've already received on the proposal and the feedback that we _will_ receive from the discussion.

**Comment by jonpugh** [comment]
It wasn't my intent to "brand as the successor" to Aegir, but to note that this is inspired by it.

I can understand that the nuance of the language matters, and am more than willing to adjust it.

This project was inspired directly from those conversations we had in LA. In fact my first notes and the idea for the name came to me the very next day.

This project started as a proof of concept and rapidly proved to be functional, and will be in production shortly.

It's got a new name and a new codebase specifically so that we can operate beyond the scope of "Aegir", to try things, experiment, and to create something new without limitation

Since the first few days of this prototype I've made an effort to keep this project open to contribution of code, design, and purpose.  We do hold the thoughts of the community in very high regard, and are focusing the design on the users. 

The thing is, "the community " is much broader than just the Aegir community, and our needs are clear, so we are moving forward in building a solution with the goal of serving everyone. 

We hope to serve the Aegir community because our our solutions deliver the same result, and we could all benefit from collaboration.

I will tone down the implication that this is "the" successor to Aegir so as to not imply that a decision was made.  I apologize that this is how it came across.

**Comment by cweagans** [comment]
Thanks, Jon. Much appreciated.

One piece of advice:

> This project started as a proof of concept and rapidly proved to be functional, and will be in production shortly.

Aegir left a bad taste in a lot of people's mouth claiming it was 'production ready' before that was actually the case. Based on past experience, I'd advise being really conservative about when you slap that particular label on.

**Comment by cweagans** [comment]
(even if you _are_ running it in production)

**Comment by jonpugh** [comment]
I've changed the language in the README.md

@cweagans  please feel free to re-open if you find anything else you would change.

**Comment by cweagans** [comment]
:+1: thanks!
